// This file is auto-generated by @hey-api/openapi-ts

import { type MutationOptions, queryOptions } from '@tanstack/solid-query';

import { client } from '../client.gen';
import { createItemUserUserIdItemNewPut, deleteItemUserUserIdItemItemIdDelete, getCategoriesCategoryAllGet, getCategoryCategoryCategoryIdGet, getUserItemsUserUserIdItemAllGet, getUserItemUserUserIdItemItemIdGet, getUsersUserAllGet, getUserUserUserIdGet, healthCheckHealthGet, type Options, sseEndpointSseGet, updateItemUserUserIdItemItemIdPatch } from '../sdk.gen';
import type { CreateItemUserUserIdItemNewPutData, CreateItemUserUserIdItemNewPutError, CreateItemUserUserIdItemNewPutResponse, DeleteItemUserUserIdItemItemIdDeleteData, DeleteItemUserUserIdItemItemIdDeleteError, DeleteItemUserUserIdItemItemIdDeleteResponse, GetCategoriesCategoryAllGetData, GetCategoryCategoryCategoryIdGetData, GetUserItemsUserUserIdItemAllGetData, GetUserItemUserUserIdItemItemIdGetData, GetUsersUserAllGetData, GetUserUserUserIdGetData, HealthCheckHealthGetData, SseEndpointSseGetData, UpdateItemUserUserIdItemItemIdPatchData, UpdateItemUserUserIdItemItemIdPatchError, UpdateItemUserUserIdItemItemIdPatchResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getUsersUserAllGetQueryKey = (options?: Options<GetUsersUserAllGetData>) => createQueryKey('getUsersUserAllGet', options);

/**
 * Get Users
 */
export const getUsersUserAllGetOptions = (options?: Options<GetUsersUserAllGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsersUserAllGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersUserAllGetQueryKey(options)
    });
};

export const getUserUserUserIdGetQueryKey = (options: Options<GetUserUserUserIdGetData>) => createQueryKey('getUserUserUserIdGet', options);

/**
 * Get User
 */
export const getUserUserUserIdGetOptions = (options: Options<GetUserUserUserIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserUserUserIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserUserUserIdGetQueryKey(options)
    });
};

export const getCategoriesCategoryAllGetQueryKey = (options?: Options<GetCategoriesCategoryAllGetData>) => createQueryKey('getCategoriesCategoryAllGet', options);

/**
 * Get Categories
 */
export const getCategoriesCategoryAllGetOptions = (options?: Options<GetCategoriesCategoryAllGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategoriesCategoryAllGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCategoriesCategoryAllGetQueryKey(options)
    });
};

export const getCategoryCategoryCategoryIdGetQueryKey = (options: Options<GetCategoryCategoryCategoryIdGetData>) => createQueryKey('getCategoryCategoryCategoryIdGet', options);

/**
 * Get Category
 */
export const getCategoryCategoryCategoryIdGetOptions = (options: Options<GetCategoryCategoryCategoryIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCategoryCategoryCategoryIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCategoryCategoryCategoryIdGetQueryKey(options)
    });
};

export const getUserItemsUserUserIdItemAllGetQueryKey = (options: Options<GetUserItemsUserUserIdItemAllGetData>) => createQueryKey('getUserItemsUserUserIdItemAllGet', options);

/**
 * Get User Items
 */
export const getUserItemsUserUserIdItemAllGetOptions = (options: Options<GetUserItemsUserUserIdItemAllGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserItemsUserUserIdItemAllGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserItemsUserUserIdItemAllGetQueryKey(options)
    });
};

/**
 * Delete Item
 */
export const deleteItemUserUserIdItemItemIdDeleteMutation = (options?: Partial<Options<DeleteItemUserUserIdItemItemIdDeleteData>>): MutationOptions<DeleteItemUserUserIdItemItemIdDeleteResponse, DeleteItemUserUserIdItemItemIdDeleteError, Options<DeleteItemUserUserIdItemItemIdDeleteData>> => {
    const mutationOptions: MutationOptions<DeleteItemUserUserIdItemItemIdDeleteResponse, DeleteItemUserUserIdItemItemIdDeleteError, Options<DeleteItemUserUserIdItemItemIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteItemUserUserIdItemItemIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserItemUserUserIdItemItemIdGetQueryKey = (options: Options<GetUserItemUserUserIdItemItemIdGetData>) => createQueryKey('getUserItemUserUserIdItemItemIdGet', options);

/**
 * Get User Item
 */
export const getUserItemUserUserIdItemItemIdGetOptions = (options: Options<GetUserItemUserUserIdItemItemIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserItemUserUserIdItemItemIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserItemUserUserIdItemItemIdGetQueryKey(options)
    });
};

/**
 * Update Item
 */
export const updateItemUserUserIdItemItemIdPatchMutation = (options?: Partial<Options<UpdateItemUserUserIdItemItemIdPatchData>>): MutationOptions<UpdateItemUserUserIdItemItemIdPatchResponse, UpdateItemUserUserIdItemItemIdPatchError, Options<UpdateItemUserUserIdItemItemIdPatchData>> => {
    const mutationOptions: MutationOptions<UpdateItemUserUserIdItemItemIdPatchResponse, UpdateItemUserUserIdItemItemIdPatchError, Options<UpdateItemUserUserIdItemItemIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateItemUserUserIdItemItemIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create Item
 */
export const createItemUserUserIdItemNewPutMutation = (options?: Partial<Options<CreateItemUserUserIdItemNewPutData>>): MutationOptions<CreateItemUserUserIdItemNewPutResponse, CreateItemUserUserIdItemNewPutError, Options<CreateItemUserUserIdItemNewPutData>> => {
    const mutationOptions: MutationOptions<CreateItemUserUserIdItemNewPutResponse, CreateItemUserUserIdItemNewPutError, Options<CreateItemUserUserIdItemNewPutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createItemUserUserIdItemNewPut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const sseEndpointSseGetQueryKey = (options?: Options<SseEndpointSseGetData>) => createQueryKey('sseEndpointSseGet', options);

/**
 * Sse Endpoint
 */
export const sseEndpointSseGetOptions = (options?: Options<SseEndpointSseGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await sseEndpointSseGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: sseEndpointSseGetQueryKey(options)
    });
};

export const healthCheckHealthGetQueryKey = (options?: Options<HealthCheckHealthGetData>) => createQueryKey('healthCheckHealthGet', options);

/**
 * Health Check
 */
export const healthCheckHealthGetOptions = (options?: Options<HealthCheckHealthGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await healthCheckHealthGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: healthCheckHealthGetQueryKey(options)
    });
};
