// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateItemUserUserIdItemNewPutData, CreateItemUserUserIdItemNewPutErrors, CreateItemUserUserIdItemNewPutResponses, DeleteItemUserUserIdItemItemIdDeleteData, DeleteItemUserUserIdItemItemIdDeleteErrors, DeleteItemUserUserIdItemItemIdDeleteResponses, GetCategoriesCategoryAllGetData, GetCategoriesCategoryAllGetErrors, GetCategoriesCategoryAllGetResponses, GetCategoryCategoryCategoryIdGetData, GetCategoryCategoryCategoryIdGetErrors, GetCategoryCategoryCategoryIdGetResponses, GetUserItemsUserUserIdItemAllGetData, GetUserItemsUserUserIdItemAllGetErrors, GetUserItemsUserUserIdItemAllGetResponses, GetUserItemUserUserIdItemItemIdGetData, GetUserItemUserUserIdItemItemIdGetErrors, GetUserItemUserUserIdItemItemIdGetResponses, GetUsersUserAllGetData, GetUsersUserAllGetErrors, GetUsersUserAllGetResponses, GetUserUserUserIdGetData, GetUserUserUserIdGetErrors, GetUserUserUserIdGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, SseEndpointSseGetData, SseEndpointSseGetResponses, UpdateItemUserUserIdItemItemIdPatchData, UpdateItemUserUserIdItemItemIdPatchErrors, UpdateItemUserUserIdItemItemIdPatchResponses } from './types.gen';
import { zCreateItemUserUserIdItemNewPutData, zCreateItemUserUserIdItemNewPutResponse, zDeleteItemUserUserIdItemItemIdDeleteData, zDeleteItemUserUserIdItemItemIdDeleteResponse, zGetCategoriesCategoryAllGetData, zGetCategoriesCategoryAllGetResponse, zGetCategoryCategoryCategoryIdGetData, zGetCategoryCategoryCategoryIdGetResponse, zGetUserItemsUserUserIdItemAllGetData, zGetUserItemsUserUserIdItemAllGetResponse, zGetUserItemUserUserIdItemItemIdGetData, zGetUserItemUserUserIdItemItemIdGetResponse, zGetUsersUserAllGetData, zGetUsersUserAllGetResponse, zGetUserUserUserIdGetData, zGetUserUserUserIdGetResponse, zHealthCheckHealthGetData, zHealthCheckHealthGetResponse, zSseEndpointSseGetData, zSseEndpointSseGetResponse, zUpdateItemUserUserIdItemItemIdPatchData, zUpdateItemUserUserIdItemItemIdPatchResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Users
 */
export const getUsersUserAllGet = <ThrowOnError extends boolean = false>(options?: Options<GetUsersUserAllGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersUserAllGetResponses, GetUsersUserAllGetErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetUsersUserAllGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetUsersUserAllGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/all',
        ...options
    });
};

/**
 * Get User
 */
export const getUserUserUserIdGet = <ThrowOnError extends boolean = false>(options: Options<GetUserUserUserIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserUserUserIdGetResponses, GetUserUserUserIdGetErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetUserUserUserIdGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetUserUserUserIdGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{user_id}',
        ...options
    });
};

/**
 * Get Categories
 */
export const getCategoriesCategoryAllGet = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesCategoryAllGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCategoriesCategoryAllGetResponses, GetCategoriesCategoryAllGetErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetCategoriesCategoryAllGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetCategoriesCategoryAllGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category/all',
        ...options
    });
};

/**
 * Get Category
 */
export const getCategoryCategoryCategoryIdGet = <ThrowOnError extends boolean = false>(options: Options<GetCategoryCategoryCategoryIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCategoryCategoryCategoryIdGetResponses, GetCategoryCategoryCategoryIdGetErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetCategoryCategoryCategoryIdGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetCategoryCategoryCategoryIdGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/category/{category_id}',
        ...options
    });
};

/**
 * Get User Items
 */
export const getUserItemsUserUserIdItemAllGet = <ThrowOnError extends boolean = false>(options: Options<GetUserItemsUserUserIdItemAllGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserItemsUserUserIdItemAllGetResponses, GetUserItemsUserUserIdItemAllGetErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetUserItemsUserUserIdItemAllGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetUserItemsUserUserIdItemAllGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{user_id}/item/all',
        ...options
    });
};

/**
 * Delete Item
 */
export const deleteItemUserUserIdItemItemIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteItemUserUserIdItemItemIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteItemUserUserIdItemItemIdDeleteResponses, DeleteItemUserUserIdItemItemIdDeleteErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zDeleteItemUserUserIdItemItemIdDeleteData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zDeleteItemUserUserIdItemItemIdDeleteResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{user_id}/item/{item_id}',
        ...options
    });
};

/**
 * Get User Item
 */
export const getUserItemUserUserIdItemItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetUserItemUserUserIdItemItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserItemUserUserIdItemItemIdGetResponses, GetUserItemUserUserIdItemItemIdGetErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetUserItemUserUserIdItemItemIdGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetUserItemUserUserIdItemItemIdGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{user_id}/item/{item_id}',
        ...options
    });
};

/**
 * Update Item
 */
export const updateItemUserUserIdItemItemIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateItemUserUserIdItemItemIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdateItemUserUserIdItemItemIdPatchResponses, UpdateItemUserUserIdItemItemIdPatchErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zUpdateItemUserUserIdItemItemIdPatchData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zUpdateItemUserUserIdItemItemIdPatchResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{user_id}/item/{item_id}',
        ...options
    });
};

/**
 * Create Item
 */
export const createItemUserUserIdItemNewPut = <ThrowOnError extends boolean = false>(options: Options<CreateItemUserUserIdItemNewPutData, ThrowOnError>) => {
    return (options.client ?? client).put<CreateItemUserUserIdItemNewPutResponses, CreateItemUserUserIdItemNewPutErrors, ThrowOnError>({
        requestValidator: async (data) => {
            return await zCreateItemUserUserIdItemNewPutData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zCreateItemUserUserIdItemNewPutResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{user_id}/item/new',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Subscribe to Item Events
 *
 * Establishes a Server-Sent Events (SSE) connection to receive real-time updates for items.
 */
export const sseEndpointSseGet = <ThrowOnError extends boolean = false>(options?: Options<SseEndpointSseGetData, ThrowOnError>) => {
    return (options?.client ?? client).sse.get<SseEndpointSseGetResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zSseEndpointSseGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zSseEndpointSseGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sse',
        ...options
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zHealthCheckHealthGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zHealthCheckHealthGetResponse.parseAsync(data);
        },
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/health',
        ...options
    });
};
