// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://spize.wranglers-software.sk' | (string & {});
};

/**
 * CategoryResponse
 */
export type CategoryResponse = {
    /**
     * Id
     *
     * Category ID
     */
    id: number;
    /**
     * Name
     *
     * Category name
     */
    name: string;
};

/**
 * GenericResponse
 */
export type GenericResponse = {
    /**
     * Message
     *
     * Generic response message
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Status
     *
     * Health status
     */
    status: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Name
     *
     * Item name
     */
    name: string;
    /**
     * Full Quantity
     *
     * Full quantity
     */
    full_quantity: number;
    /**
     * Category Id
     *
     * Category ID
     */
    category_id: number;
    /**
     * Note
     *
     * Item note
     */
    note: string;
};

/**
 * ItemResponse
 */
export type ItemResponse = {
    /**
     * Id
     *
     * Item ID
     */
    id: number;
    /**
     * Category Id
     *
     * Category ID
     */
    category_id: number;
    /**
     * Name
     *
     * Item name
     */
    name: string;
    /**
     * Full Quantity
     *
     * Full quantity
     */
    full_quantity: number;
    /**
     * Current Quantity
     *
     * Current quantity
     */
    current_quantity: number;
    /**
     * Note
     *
     * Item note
     */
    note: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     *
     * User ID
     */
    id: number;
    /**
     * Name
     *
     * User name
     */
    name: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetUsersUserAllGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/all';
};

export type GetUsersUserAllGetResponses = {
    /**
     * Response Get Users User All Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type GetUsersUserAllGetResponse = GetUsersUserAllGetResponses[keyof GetUsersUserAllGetResponses];

export type GetUserUserUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the user
         */
        user_id: number;
    };
    query?: never;
    url: '/user/{user_id}';
};

export type GetUserUserUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUserUserIdGetError = GetUserUserUserIdGetErrors[keyof GetUserUserUserIdGetErrors];

export type GetUserUserUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserUserUserIdGetResponse = GetUserUserUserIdGetResponses[keyof GetUserUserUserIdGetResponses];

export type GetCategoriesCategoryAllGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/category/all';
};

export type GetCategoriesCategoryAllGetResponses = {
    /**
     * Response Get Categories Category All Get
     *
     * Successful Response
     */
    200: Array<CategoryResponse>;
};

export type GetCategoriesCategoryAllGetResponse = GetCategoriesCategoryAllGetResponses[keyof GetCategoriesCategoryAllGetResponses];

export type GetCategoryCategoryCategoryIdGetData = {
    body?: never;
    path: {
        /**
         * Category Id
         *
         * The ID of the category
         */
        category_id: number;
    };
    query?: never;
    url: '/category/{category_id}';
};

export type GetCategoryCategoryCategoryIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCategoryCategoryCategoryIdGetError = GetCategoryCategoryCategoryIdGetErrors[keyof GetCategoryCategoryCategoryIdGetErrors];

export type GetCategoryCategoryCategoryIdGetResponses = {
    /**
     * Successful Response
     */
    200: CategoryResponse;
};

export type GetCategoryCategoryCategoryIdGetResponse = GetCategoryCategoryCategoryIdGetResponses[keyof GetCategoryCategoryCategoryIdGetResponses];

export type GetUserItemsUserUserIdItemAllGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the user
         */
        user_id: number;
    };
    query?: never;
    url: '/user/{user_id}/item/all';
};

export type GetUserItemsUserUserIdItemAllGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserItemsUserUserIdItemAllGetError = GetUserItemsUserUserIdItemAllGetErrors[keyof GetUserItemsUserUserIdItemAllGetErrors];

export type GetUserItemsUserUserIdItemAllGetResponses = {
    /**
     * Response Get User Items User  User Id  Item All Get
     *
     * Successful Response
     */
    200: Array<ItemResponse>;
};

export type GetUserItemsUserUserIdItemAllGetResponse = GetUserItemsUserUserIdItemAllGetResponses[keyof GetUserItemsUserUserIdItemAllGetResponses];

export type DeleteItemUserUserIdItemItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the user
         */
        user_id: number;
        /**
         * Item Id
         *
         * The ID of the item
         */
        item_id: number;
    };
    query?: never;
    url: '/user/{user_id}/item/{item_id}';
};

export type DeleteItemUserUserIdItemItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteItemUserUserIdItemItemIdDeleteError = DeleteItemUserUserIdItemItemIdDeleteErrors[keyof DeleteItemUserUserIdItemItemIdDeleteErrors];

export type DeleteItemUserUserIdItemItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type DeleteItemUserUserIdItemItemIdDeleteResponse = DeleteItemUserUserIdItemItemIdDeleteResponses[keyof DeleteItemUserUserIdItemItemIdDeleteResponses];

export type GetUserItemUserUserIdItemItemIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the user
         */
        user_id: number;
        /**
         * Item Id
         *
         * The ID of the item
         */
        item_id: number;
    };
    query?: never;
    url: '/user/{user_id}/item/{item_id}';
};

export type GetUserItemUserUserIdItemItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserItemUserUserIdItemItemIdGetError = GetUserItemUserUserIdItemItemIdGetErrors[keyof GetUserItemUserUserIdItemItemIdGetErrors];

export type GetUserItemUserUserIdItemItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ItemResponse;
};

export type GetUserItemUserUserIdItemItemIdGetResponse = GetUserItemUserUserIdItemItemIdGetResponses[keyof GetUserItemUserUserIdItemItemIdGetResponses];

export type UpdateItemUserUserIdItemItemIdPatchData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the user
         */
        user_id: number;
        /**
         * Item Id
         *
         * The ID of the item
         */
        item_id: number;
    };
    query?: {
        /**
         * Name
         *
         * The new name of the item
         */
        name?: string;
        /**
         * Full Quantity
         *
         * The new full quantity of the item
         */
        full_quantity?: number;
        /**
         * Quantity
         *
         * The new quantity of the item
         */
        quantity?: number;
        /**
         * Category Id
         *
         * The new category ID of the item
         */
        category_id?: number;
        /**
         * Note
         *
         * The new note of the item
         */
        note?: string;
    };
    url: '/user/{user_id}/item/{item_id}';
};

export type UpdateItemUserUserIdItemItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemUserUserIdItemItemIdPatchError = UpdateItemUserUserIdItemItemIdPatchErrors[keyof UpdateItemUserUserIdItemItemIdPatchErrors];

export type UpdateItemUserUserIdItemItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type UpdateItemUserUserIdItemItemIdPatchResponse = UpdateItemUserUserIdItemItemIdPatchResponses[keyof UpdateItemUserUserIdItemItemIdPatchResponses];

export type CreateItemUserUserIdItemNewPutData = {
    /**
     * The item to create
     */
    body: ItemCreate;
    path: {
        /**
         * User Id
         *
         * The ID of the user
         */
        user_id: number;
    };
    query?: never;
    url: '/user/{user_id}/item/new';
};

export type CreateItemUserUserIdItemNewPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemUserUserIdItemNewPutError = CreateItemUserUserIdItemNewPutErrors[keyof CreateItemUserUserIdItemNewPutErrors];

export type CreateItemUserUserIdItemNewPutResponses = {
    /**
     * Successful Response
     */
    200: GenericResponse;
};

export type CreateItemUserUserIdItemNewPutResponse = CreateItemUserUserIdItemNewPutResponses[keyof CreateItemUserUserIdItemNewPutResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];
