// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CategoryResponse
 */
export const zCategoryResponse = z.object({
    id: z.int(),
    name: z.string()
});

/**
 * GenericResponse
 */
export const zGenericResponse = z.object({
    message: z.string()
});

/**
 * HealthResponse
 */
export const zHealthResponse = z.object({
    status: z.string()
});

/**
 * ItemCreate
 */
export const zItemCreate = z.object({
    name: z.string(),
    full_quantity: z.int().gte(1),
    current_quantity: z.int().gte(0),
    category_id: z.int(),
    note: z.string()
});

/**
 * ItemResponse
 */
export const zItemResponse = z.object({
    id: z.int(),
    category_id: z.int(),
    name: z.string(),
    full_quantity: z.int().gte(1),
    current_quantity: z.int().gte(0),
    note: z.string()
});

/**
 * UserResponse
 */
export const zUserResponse = z.object({
    id: z.int(),
    name: z.string()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zGetUsersUserAllGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response 200 Get Users User All Get
 *
 * Successful Response
 */
export const zGetUsersUserAllGetResponse = z.array(zUserResponse);

export const zGetUserUserUserIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetUserUserUserIdGetResponse = zUserResponse;

export const zGetCategoriesCategoryAllGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response 200 Get Categories Category All Get
 *
 * Successful Response
 */
export const zGetCategoriesCategoryAllGetResponse = z.array(zCategoryResponse);

export const zGetCategoryCategoryCategoryIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        category_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetCategoryCategoryCategoryIdGetResponse = zCategoryResponse;

export const zGetUserItemsUserUserIdItemAllGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Response 200 Get User Items User  User Id  Item All Get
 *
 * Successful Response
 */
export const zGetUserItemsUserUserIdItemAllGetResponse = z.array(zItemResponse);

export const zDeleteItemUserUserIdItemItemIdDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.int(),
        item_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeleteItemUserUserIdItemItemIdDeleteResponse = zGenericResponse;

export const zGetUserItemUserUserIdItemItemIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.int(),
        item_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetUserItemUserUserIdItemItemIdGetResponse = zItemResponse;

export const zUpdateItemUserUserIdItemItemIdPatchData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        user_id: z.int(),
        item_id: z.int()
    }),
    query: z.optional(z.object({
        name: z.optional(z.string()),
        full_quantity: z.optional(z.int().gte(1)),
        quantity: z.optional(z.int().gte(0)),
        category_id: z.optional(z.int()),
        note: z.optional(z.string())
    }))
});

/**
 * Successful Response
 */
export const zUpdateItemUserUserIdItemItemIdPatchResponse = zGenericResponse;

export const zCreateItemUserUserIdItemNewPutData = z.object({
    body: zItemCreate,
    path: z.object({
        user_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Response Create Item User  User Id  Item New Put
 *
 * Successful Response
 */
export const zCreateItemUserUserIdItemNewPutResponse = z.int();

export const zSseEndpointSseGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zHealthCheckHealthGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zHealthCheckHealthGetResponse = zHealthResponse;
